# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\artETmétiers\_2e année\SAVOIR\OPM\zeiss_converter\menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 222)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.UI_BUTTON_CHOOSE = QtWidgets.QPushButton(self.centralwidget)
        self.UI_BUTTON_CHOOSE.setObjectName("UI_BUTTON_CHOOSE")
        self.verticalLayout_2.addWidget(self.UI_BUTTON_CHOOSE)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(25, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UI_RADIO_ZEISS = QtWidgets.QRadioButton(self.centralwidget)
        self.UI_RADIO_ZEISS.setObjectName("UI_RADIO_ZEISS")
        self.verticalLayout_3.addWidget(self.UI_RADIO_ZEISS)
        self.UI_RADIO_P16 = QtWidgets.QRadioButton(self.centralwidget)
        self.UI_RADIO_P16.setObjectName("UI_RADIO_P16")
        self.verticalLayout_3.addWidget(self.UI_RADIO_P16)
        self.UI_BUTTON_CONVERT = QtWidgets.QPushButton(self.centralwidget)
        self.UI_BUTTON_CONVERT.setObjectName("UI_BUTTON_CONVERT")
        self.verticalLayout_3.addWidget(self.UI_BUTTON_CONVERT)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(25, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.UI_LABEL_PLOT = QtWidgets.QLabel(self.centralwidget)
        self.UI_LABEL_PLOT.setAlignment(QtCore.Qt.AlignCenter)
        self.UI_LABEL_PLOT.setObjectName("UI_LABEL_PLOT")
        self.verticalLayout.addWidget(self.UI_LABEL_PLOT)
        self.UI_BUTTON_SAVE = QtWidgets.QPushButton(self.centralwidget)
        self.UI_BUTTON_SAVE.setObjectName("UI_BUTTON_SAVE")
        self.verticalLayout.addWidget(self.UI_BUTTON_SAVE)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setMinimumSize(QtCore.QSize(25, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.UI_LABEL_LOGO_VALIDER = QtWidgets.QLabel(self.centralwidget)
        self.UI_LABEL_LOGO_VALIDER.setAlignment(QtCore.Qt.AlignCenter)
        self.UI_LABEL_LOGO_VALIDER.setObjectName("UI_LABEL_LOGO_VALIDER")
        self.verticalLayout_4.addWidget(self.UI_LABEL_LOGO_VALIDER)
        self.UI_BUTTON_AGAIN = QtWidgets.QPushButton(self.centralwidget)
        self.UI_BUTTON_AGAIN.setObjectName("UI_BUTTON_AGAIN")
        self.verticalLayout_4.addWidget(self.UI_BUTTON_AGAIN)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.UI_TEXT_VERSION_NUMBER = QtWidgets.QLabel(self.centralwidget)
        self.UI_TEXT_VERSION_NUMBER.setObjectName("UI_TEXT_VERSION_NUMBER")
        self.horizontalLayout_2.addWidget(self.UI_TEXT_VERSION_NUMBER)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "logo_ajouter"))
        self.UI_BUTTON_CHOOSE.setText(_translate("MainWindow", "Choisir un fichier"))
        self.UI_RADIO_ZEISS.setText(_translate("MainWindow", "Archi-vénérable Zei\'ss"))
        self.UI_RADIO_P16.setText(_translate("MainWindow", "P16+"))
        self.UI_BUTTON_CONVERT.setText(_translate("MainWindow", "Convertir"))
        self.UI_LABEL_PLOT.setText(_translate("MainWindow", "plot_graph"))
        self.UI_BUTTON_SAVE.setText(_translate("MainWindow", "Enregistrer"))
        self.label_3.setText(_translate("MainWindow", "Le fichier n\'est pas enregistré"))
        self.UI_LABEL_LOGO_VALIDER.setText(_translate("MainWindow", "logo_valider"))
        self.UI_BUTTON_AGAIN.setText(_translate("MainWindow", "Convertir un autre fichier"))
        self.label_6.setText(_translate("MainWindow", "Squall\'ss 4Li218"))
        self.label_7.setText(_translate("MainWindow", "Kar\'sCarate\'ss 129Li218"))
        self.UI_TEXT_VERSION_NUMBER.setText(_translate("MainWindow", "version_number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
